/// <reference types="expo/types" />

// NOTE: This file enables the typed Expo config/environment surface
// (process.env.EXPO_PUBLIC_*, Constants.expoConfig types). It is normally
// regenerated by `expo customize tsconfig.json`; it is hand-written here
// so `pnpm --filter mobile typecheck` works without an interactive step.